# Generated by Django 2.0.2 on 2018-02-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordsfinder', '0005_auto_20180208_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='words',
            new_name='word',
        ),
    ]
