# Generated by Django 2.0.2 on 2018-02-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordsfinder', '0006_auto_20180208_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='word',
            new_name='words',
        ),
    ]
