# Generated by Django 2.0.2 on 2018-02-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordsfinder', '0007_auto_20180208_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictionary',
        ),
    ]
